[workspace]
members = [
  "kokoro-core",
  "kokoro-default-impl",
  "kokoro-dynamic-plugin",
  "kokoro-macros",
  "examples/dynamic-plugin",
  "examples/dynamic-plugin/plugin-example"
]

[package]
name = "kokoro"
version = "0.0.7"
edition = "2021"

[features]
default = ["macros", "default-impl", "dynamic-plugin"]
nightly = ["kokoro-core/nightly"]
macros = ["dep:kokoro-macros"]
default-impl = ["dep:kokoro-default-impl"]
dynamic-plugin = ["dep:kokoro-dynamic-plugin"]

[dependencies.kokoro-core]
version = "0.0.9"
path = "./kokoro-core"

[dependencies.kokoro-default-impl]
version = "0.0.9"
path = "./kokoro-default-impl"
optional = true

[dependencies.kokoro-macros]
version = "0.1.0"
path = "./kokoro-macros"
optional = true

[dependencies.kokoro-dynamic-plugin]
version = "0.0.3"
path = "./kokoro-dynamic-plugin"
optional = true
