[workspace]
members = ["kokoro-core", "kokoro-default-impl", "kokoro-macros"]

[package]
name = "kokoro"
edition = "2021"

[features]
default = ["macros","default-impl"]
nightly = ["kokoro-core/nightly"]
macros = ["dep:kokoro-macros"]
default-impl = ["dep:kokoro-default-impl"]

[dependencies.kokoro-core]
version = "0.0.9"
path = "./kokoro-core"

[dependencies.kokoro-default-impl]
version = "0.0.9"
path = "./kokoro-default-impl"
optional = true

[dependencies.kokoro-macros]
version = "0.1.0"
path = "./kokoro-macros"
optional = true
