[package]
name = "kokoro-macros"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/Kokoro-rs/kokoro/tree/main/kokoro-macros"

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.48"

[lib]
proc-macro = true
