[package]
name = "dynamic-plugin"
version = "0.1.0"
edition = "2021"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.kokoro]
path = "../../"

[dependencies.plugin-example]
path = "./plugin-example"