[package]
name = "kokoro-dynamic-plugin"
version = "0.0.3"
edition = "2021"

[dependencies]
libloading = "^0.8.1"
[dependencies.kokoro-core]
path = "../kokoro-core"
version = "0.0.9"
[dependencies.kokoro-default-impl]
path = "../kokoro-default-impl"
version = "0.0.9"
