[package]
name = "kokoro"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime.workspace = true
wasmtime-wasi.workspace = true
dashmap.workspace = true
anyhow.workspace = true
nom.workspace = true
